name = "DirectDependents"
uuid = "94bb4f33-2dc8-49c0-b61a-c34618d74b87"
authors = ["Daniel Schwabeneder <daschw@disroot.org>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
